alitr/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_app.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]

main_app/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from . import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns



urlpatterns = [
    path('', views.home, name='home'),
    path('about/', views.about, name='about'),
    # Job Apps
    path('jobs/', views.jobs_index, name='index'),
    path('jobs/<int:job_id>/', views.jobs_detail, name='detail'),
    path('jobs/create/', views.JobCreate.as_view(), name='jobs_create'),
    path('jobs/<int:pk>/update/', views.JobUpdate.as_view(), name='jobs_update'),
    path('jobs/<int:pk>/delete/', views.JobDelete.as_view(), name='jobs_delete'),
    # Status
    path('jobs/<int:job_id>/add_status/', views.add_status, name='add_status'),
    path('status/<int:status_id>/update/', views.update_status, name='update_status'),
    path('status/<int:status_id>/delete/', views.delete_status, name='delete_status'),
    # Company

    # User
    path('accounts/signup', views.signup, name='signup'),
    #Profile 
    path('profile/update',views.profile_update, name='profile_update'),
    path('profile/',views.profile, name='profile'),
    path('profile/<int:pro_id>/add_photo/', views.add_photo, name='add_photo'),

    #Skills
    path('skills/', views.SkillList.as_view(), name='skills_index'),
    path('skills/<int:pk>/', views.SkillDetail.as_view(), name='skills_detail'),
    path('skills/create/', views.SkillCreate.as_view(), name='skills_create'),
    path('skills/<int:pk>/update/', views.SkillUpdate.as_view(), name='skills_update'),
    path('skills/<int:pk>/delete/', views.SkillDelete.as_view(), name='skills_delete'),



    
]

urlpatterns += staticfiles_urlpatterns() + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main_app/models.py
# Create your models here.
from django.db import models
from django.contrib.auth.models import User
from django.db.models.deletion import CASCADE
from django.urls import reverse #matching url
from PIL import Image

# Create your models here.
class Job_application(models.Model):
    name = models.CharField(max_length=100)
    company = models.CharField(max_length=100)
    location = models.CharField(max_length=250)
    date = models.DateField('Date Applied')
    url = models.CharField(
        max_length=250,
        blank=True
        )
    requirements = models.TextField(
        max_length=500,
        blank=True
        )
    notes = models.TextField(
        max_length=500,
        blank=True
        )
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('detail', kwargs={'job_id': self.id}) #every model instance has its own method 
        #django will now render the detail page, 

class Attachment(models.Model): # will implement later with AWS if possible -CO
    url = models.CharField(max_length=250)
    job_app = models.ForeignKey(Job_application, on_delete=models.CASCADE)

    def __str__(self):
        return f'Attachment for job_id: {self.job_id} @{self.url}'

class Status(models.Model):
  date = models.DateField('Date')

  STATUS = (
        ('A', 'Applied'),
        ('B', 'In Progress'),
        ('C', 'Interview scheduled'),
        ('D', 'Interview complete'),
        ('E', 'Job Offer'),
        ('F', 'Incomplete'),
        ('G', 'Not Selected'),
        ('H', 'Unknown'),
  )
 
  status = models.CharField(
    max_length=1,
    choices=STATUS,
    default=STATUS[0][0]
  )

  job_app = models.ForeignKey(Job_application, on_delete=models.CASCADE)

  def __str__(self):
    # Nice method for obtaining the friendly value of a Field.choice
    return f"{self.get_status_display()}"

  # change the default sort
  class Meta:
    ordering = ['-date']
    verbose_name_plural = 'Status'

# placeholder for Company model if possible -CO

#User Profile model 
class Skill(models.Model):

  SKILL = (
    ('1','Level 1'),
    ('2','Level 2'),
    ('3','Level 3'),
    ('4','Level 4'),
    ('5','Level 5'),
  )

  name = models.CharField(
    max_length=100,
    blank=True
  )
  level = models.CharField(
    max_length=1,
    choices=SKILL,
    default=SKILL[0][0]
  )

  user = models.ForeignKey(User, on_delete=models.CASCADE)
  def __str__(self):
    return self.name

  def get_absolute_url(self):
    return reverse('profile')

#Profile Model 
class Pro(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE) # Delete profile when user is deleted
    image = models.ImageField(default='default.jpg', upload_to='profile_pics')
    experience = models.TextField(max_length=1000, blank=True)
    goals = models.TextField(max_length=1000, blank=True)

    def __str__(self):
        return f'{self.user.username} Pro' #show how we want it to be displayed
    
    class Meta:
        verbose_name_plural = 'pro'
    
    # Override the save method of the model
    def save(self, *args, **kwargs):
        super(Pro, self).save(*args, **kwargs)

        img = Image.open(self.image.path) # Open image
        
        # resize image
        if img.height > 300 or img.width > 300:
            output_size = (300, 300)
            img.thumbnail(output_size) # Resize image
            img.save(self.image.path) # Save it again and override the larger image

# Profile Photo Model
class Photo(models.Model):
  url = models.CharField(max_length=200)
  profile = models.ForeignKey(Pro, on_delete=models.CASCADE)

  def __str__(self):
        return f"Photo for profile_id: {self.profile_id} @{self.url}"

main_app/forms.py
from django.forms import ModelForm
from .models import Status, Pro
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm


class StatusForm(ModelForm):
    class Meta:
        model = Status
        fields = ['date', 'status']


class UserRegisterForm(UserCreationForm):
    email = forms.EmailField()

    # Configuration
    class Meta:
        model = User
        fields = ['username', 'email','first_name','last_name', 'password1', 'password2']


# Create a UserUpdateForm to update username and email
class UserUpdateForm(forms.ModelForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['username', 'email', 'first_name', 'last_name']

# Create a ProfileUpdateForm to update image
class ProfileUpdateForm(forms.ModelForm):
    class Meta:
        model = Pro
        fields = ['experience', 'goals']

main_app/views.py
from django.http.response import HttpResponseRedirect
from .forms import StatusForm
from .models import Job_application, Status,Skill, Pro, Photo
from os import error
from django.shortcuts import get_object_or_404, render, redirect
from django.urls import reverse
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic import ListView, DetailView
from django.contrib import messages
from .forms import UserRegisterForm, UserUpdateForm, ProfileUpdateForm # Import the form we just created

# for AWS
import boto3
import uuid
# AWS constants
S3_BASE_URL = 'https://s3-us-west-1.amazonaws.com/'
BUCKET = 'alitr'

# imports for user authentication
from django.contrib.auth.models import User
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin

# Create your views here.

def home(request):
    return render(request, 'home.html')

def about(request):
    return render(request, 'about.html')

@login_required
def jobs_index(request):
    jobs = Job_application.objects.filter(user=request.user).order_by('-date')
    statuses = []
    for job in jobs:
        latest_status = Status.objects.filter(job_app=job).first()
        statuses.append(latest_status)
    
    return render(request, 'jobs/index.html', {
        'jobs': jobs, 
        'statuses': statuses,
    })

@login_required
def jobs_detail(request, job_id):
    job = Job_application.objects.get(id=job_id)
    status_form = StatusForm()
    status = Status.objects.filter(job_app=job_id).first()

    return render(request, 'jobs/detail.html', {
        'job': job,
        'status': status,
        'status_form': status_form,
    })

def register(request):
    if request.method == 'POST':
        form = UserRegisterForm(request.POST) 
        if form.is_valid():
            form.save() # Save user to Database
            username = form.cleaned_data.get('username') # Get the username that is submitted
            messages.success(request, f'Account created for {username}!') # Show sucess message when account is created
            return redirect('blog-home') # Redirect user to Homepage
    else:
        form = UserRegisterForm()
    return render(request, 'users/register.html', {'form': form})

class JobCreate(CreateView):
    model = Job_application
    fields = ['name', 'company', 'location', 'date', 'url', 'requirements', 'notes']

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)

class JobUpdate(UpdateView):
    model = Job_application
    fields = ['name', 'company', 'location', 'date', 'url', 'requirements', 'notes']

class JobDelete(DeleteView):
    model = Job_application
    success_url = '/jobs/'

#StatusViews
@login_required
def add_status(request, job_id):
    form = StatusForm(request.POST)
    if form.is_valid():
        new_status = form.save(commit=False)
        new_status.job_app_id = job_id
        new_status.save()
    
    return redirect('detail', job_id=job_id)

@login_required
def update_status(request, status_id):
    status = get_object_or_404(Status, id=status_id)

    if request.method != 'POST':
        form = StatusForm(instance=status)

    else:
        form = StatusForm(instance=status, data=request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('detail', args=[status.job_app.id]))
             
    return render(request, 'status/update.html', {'form': form, 'status': status })

@login_required
def delete_status(request, status_id):
    status = get_object_or_404(Status, id=status_id)
    if request.method == 'POST':
        status.delete()
        return HttpResponseRedirect(reverse('detail', args=[status.job_app.id]))

    return render(request, 'status/delete.html', {'status': status})

# Skill Views
class SkillList(LoginRequiredMixin, ListView):
  model = Skill

class SkillDetail(LoginRequiredMixin, DetailView):
  model = Skill

class SkillCreate(LoginRequiredMixin, CreateView):
  model = Skill
  fields = ['name','level']
  
  def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)

class SkillUpdate(LoginRequiredMixin, UpdateView):
  model = Skill
  fields = ['name','level']
  
class SkillDelete(LoginRequiredMixin, DeleteView):
  model = Skill
  success_url = '/skills/'

# Register Def

def signup(request):
    if request.method == 'POST':
        form = UserRegisterForm(request.POST) 
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username') 
            messages.success(request, f'Your account has been created! You are now able to log in') 
            return redirect('login')
    else:
        form = UserRegisterForm()
    return render(request, 'registration/signup.html', {'form': form})

# Update it here
@login_required
def profile_update(request):
    if request.method == 'POST':
        u_form = UserUpdateForm(request.POST, instance=request.user)
        p_form = ProfileUpdateForm(request.POST,
                                   request.FILES,
                                   instance=request.user.pro) 
        if u_form.is_valid() and p_form.is_valid():
            u_form.save()
            p_form.save()
            messages.success(request, f'Your account has been updated!')
            return redirect('profile') # Redirect back to profile page

    else:
        u_form = UserUpdateForm(instance=request.user)
        p_form = ProfileUpdateForm(instance=request.user.pro)

    photo = Photo.objects.filter(profile=request.user.pro).last()

    context = {
        'u_form': u_form,
        'p_form': p_form,
        'profile': request.user.pro,
        'photo': photo
    }

    return render(request, 'profile/update.html', context)

def profile(request):
    profile = request.user.pro
    skills = Skill.objects.filter(user=request.user)
    photo = Photo.objects.filter(profile=request.user.pro).last()

    return render(request, 'profile/index.html', {
        'profile': profile, 
        'user': request.user, 
        'skills': skills,
        'photo': photo,
    })

def add_photo(request, pro_id):
    photo_file = request.FILES.get('photo-file', None)
    if photo_file:
        s3 = boto3.client('s3')
        # need a unique "key" for S3 / needs image file extension too
        key = uuid.uuid4().hex[:6] + photo_file.name[photo_file.name.rfind('.'):]
        # just in case something goes wrong
        try:
            s3.upload_fileobj(photo_file, BUCKET, key)
            url = f"{S3_BASE_URL}{BUCKET}/{key}"
            photo = Photo(url=url, profile_id=pro_id)
            photo.save()
        except:
            print('An error occurred uploading file to S3')

    return redirect('profile')

main_app/templates/jobs/detail.html
{% extends 'base.html' %}
{% block content %}

<h3 class="center">Job Application Details</h3>

<a href="{% url 'index' %}">&larr; Return</a>
<div class="row">
    <div class="card">
        <div class="card-content job-details">
            <p><b>Job Title:</b> {{ job.name }}</p>
            <p><b>Company:</b> {{ job.company }}</p>
            <p><b>Location:</b> {{ job.location }}</p>
            <p><b>Date Applied:</b> {{ job.date }}</p>
            <p><b>Status:</b> {{ status }}</p>
            <p><b>URL:</b> 
                {% if job.url != "" %}
                    <a href="{{ job.url }}" target="_blank">Click Here</a>
                {% else %}
                    None added
                {% endif %}
                </p>
            <br>
            <a href="{% url 'jobs_update' job.id %}"><button class="btn">Edit</button></a>
            <a href="{% url 'jobs_delete' job.id %}"><button class="btn">Delete</button></a>
        </div>
    </div>        
    <div class="card">
        <div class="card-content">
            <h5>Requirements</h5>
            <p>
                {{ job.requirements }}
            </p>
        </div>
    </div>
    <div class="card">
        <div class="card-content">
            <h5>Notes</h5>
            <p>
               {{ job.notes }} 
            </p>
        </div>
    </div>
    <div class="card">
        <div class="card-content col s8">
            <h5>Application History</h5>
            <table class="striped">
                <thead>
                    <tr>
                        <th>Date</th>
                        <th>Status</th>
                        <th></th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                    {% for status in job.status_set.all %}
                    <tr>
                        <td>{{ status.date }}</td>
                        <td>{{ status.get_status_display}}</td>
                        <td><a href="{% url 'update_status' status.id %}">Edit</a></td>
                        <td><a href="{% url 'delete_status' status.id %}">Delete</a></td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>            
        </div>
        <div class="card-content col s4">
            <form action="{% url 'add_status' job.id %}" method="post">
                {% csrf_token %}
                {{ status_form.as_p }}
                <br>
                <input type="submit" value="Update Status" class="btn">
            </form>
        </div>
    </div>
</div>

<script>
    // create datepicker
    var dateEl = document.getElementById('id_date');
    M.Datepicker.init(dateEl, {
      format: 'yyyy-mm-dd',
      defaultDate: new Date(),
      setDefaultDate: true,
      autoClose: true,
    });
  
</script>

{% endblock %}

main_app/templates/jobs/index.html
{% extends 'base.html' %}
{% block content %}

<h3 class="center">All Job Applications</h3>

<div class="row">
    <div class="col s4">
        <h4 class="center">New Jobs</h4>
        {% for status in statuses %}
            {% if status.status == 'A' %}
                <a href="{% url 'detail' status.job_app.id %}">
                    <div class="card">
                        <div class="card-content">
                            <span class="card-title">{{ status.job_app.name }}</span>
                            <p>{{ status.job_app.company }}</p>
                            <p>{{ status.job_app.location }}</p>
                            <p>{{ status.get_status_display }} on {{ status.date }}</p>
                        </div>
                    </div>
                </a>
            {% endif %}
        {% endfor %}
    </div>

    <div class="col s4">
        <h4 class="center">In Progress</h4>
        {% for status in statuses %}
            {% if status.status == 'B' %}
            <a href="{% url 'detail' status.job_app.id %}">
                <div class="card">
                    <div class="card-content">
                        <span class="card-title">{{ status.job_app.name }}</span>
                        <p>{{ status.job_app.company }}</p>
                        <p>{{ status.job_app.location }}</p>
                        <p>{{ status.get_status_display }} on {{ status.date }}</p>
                    </div>
                </div>
            </a>
            {% elif status.status == 'C' %}
            <a href="{% url 'detail' status.job_app.id %}">
                <div class="card">
                    <div class="card-content">
                        <span class="card-title">{{ status.job_app.name }}</span>
                        <p>{{ status.job_app.company }}</p>
                        <p>{{ status.job_app.location }}</p>
                        <p>{{ status.get_status_display }} on {{ status.date }}</p>
                    </div>
                </div>
            </a>
            {% elif status.status == 'D' %}
            <a href="{% url 'detail' status.job_app.id %}">
                <div class="card">
                    <div class="card-content">
                        <span class="card-title">{{ status.job_app.name }}</span>
                        <p>{{ status.job_app.company }}</p>
                        <p>{{ status.job_app.location }}</p>
                        <p>{{ status.get_status_display }} on {{ status.date }}</p>
                    </div>
                </div>
            </a>
            {% endif %}
        {% endfor %}
    </div>
    <div class="col s4">
        <h4 class="center">Outcome</h4>
        {% for status in statuses %}
            {% if status.status == 'E' %}
                <a href="{% url 'detail' status.job_app.id %}">
                    <div class="card">
                        <div class="card-content">
                            <span class="card-title">{{ status.job_app.name }}</span>
                            <p>{{ status.job_app.company }}</p>
                            <p>{{ status.job_app.location }}</p>
                            <p>{{ status.get_status_display }} on {{ status.date }}</p>
                        </div>
                    </div>
                </a>
                {% elif status.status == 'F' %}
            <a href="{% url 'detail' status.job_app.id %}">
                <div class="card">
                    <div class="card-content">
                        <span class="card-title">{{ status.job_app.name }}</span>
                        <p>{{ status.job_app.company }}</p>
                        <p>{{ status.job_app.location }}</p>
                        <p>{{ status.get_status_display }} on {{ status.date }}</p>
                    </div>
                </div>
            </a>
            {% elif status.status == 'G' %}
            <a href="{% url 'detail' status.job_app.id %}">
                <div class="card">
                    <div class="card-content">
                        <span class="card-title">{{ status.job_app.name }}</span>
                        <p>{{ status.job_app.company }}</p>
                        <p>{{ status.job_app.location }}</p>
                        <p>{{ status.get_status_display }} on {{ status.date }}</p>
                    </div>
                </div>
            </a>
            {% elif status.status == 'H' %}
            <a href="{% url 'detail' status.job_app.id %}">
                <div class="card">
                    <div class="card-content">
                        <span class="card-title">{{ status.job_app.name }}</span>
                        <p>{{ status.job_app.company }}</p>
                        <p>{{ status.job_app.location }}</p>
                        <p>{{ status.get_status_display }} on {{ status.date }}</p>
                    </div>
                </div>
            </a>
            {% endif %}
        {% endfor %}
    </div>   
</div>


{% endblock %}